<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="jagadeesh" name="com.nvidia.cosmos.controller.UserControllerTest" tests="8" failures="1" timestamp="1 Sep 2016 14:49:38 GMT" time="2.855" errors="0">
  <testcase name="listUsers" time="0.056" classname="com.nvidia.cosmos.controller.UserControllerTest"/>
  <testcase name="updateUserProfile" time="1.888" classname="com.nvidia.cosmos.controller.UserControllerTest"/>
  <testcase name="register" time="0.136" classname="com.nvidia.cosmos.controller.UserControllerTest"/>
  <testcase name="profileUpdate" time="0.039" classname="com.nvidia.cosmos.controller.UserControllerTest"/>
  <testcase name="findUserProfile" time="0.030" classname="com.nvidia.cosmos.controller.UserControllerTest"/>
  <testcase name="userDelete" time="0.040" classname="com.nvidia.cosmos.controller.UserControllerTest">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.nvidia.cosmos.controller.UserControllerTest.userDelete(UserControllerTest.java:280)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- userDelete -->
  <testcase name="updateuser" time="0.053" classname="com.nvidia.cosmos.controller.UserControllerTest"/>
  <testcase name="userValidate" time="0.613" classname="com.nvidia.cosmos.controller.UserControllerTest"/>
</testsuite> <!-- com.nvidia.cosmos.controller.UserControllerTest -->
